INSERT OR IGNORE INTO system_settings (id, key, value, type, category, created_at, updated_at)
VALUES
  ('h3-fl2va-sage-attention-20260825', 'h3-fl2va.sage_attention', 'CONFIGURE_IN_ADMIN', 'string', 'h3-fl2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-fl2va-sage-allow-compile-20260825', 'h3-fl2va.sage_allow_compile', 'false', 'boolean', 'h3-fl2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-fl2va-low-vram-head-chunks-20260825', 'h3-fl2va.low_vram_head_chunks', 'CONFIGURE_IN_ADMIN', 'number', 'h3-fl2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-sage-attention-20260825', 'h3-ref2va.sage_attention', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-sage-allow-compile-20260825', 'h3-ref2va.sage_allow_compile', 'false', 'boolean', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-low-vram-head-chunks-20260825', 'h3-ref2va.low_vram_head_chunks', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-unet-20260825', 'h3-ref2va.no_video_unet', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-steps-20260825', 'h3-ref2va.no_video_steps', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-sampler-20260825', 'h3-ref2va.no_video_sampler', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-scheduler-20260825', 'h3-ref2va.no_video_scheduler', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-megapixels-20260825', 'h3-ref2va.no_video_megapixels', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-chunk-feedforward-enabled-20260825', 'h3-ref2va.no_video_chunk_feedforward_enabled', 'false', 'boolean', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-chunk-feedforward-chunks-20260825', 'h3-ref2va.no_video_chunk_feedforward_chunks', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-chunk-feedforward-min-len-20260825', 'h3-ref2va.no_video_chunk_feedforward_min_len', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-split-step-20260825', 'h3-ref2va.no_video_split_step', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-manual-sigmas-20260825', 'h3-ref2va.no_video_manual_sigmas', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-model-20260825', 'h3-ref2va.no_video_upscaler_model', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-megapixels-20260825', 'h3-ref2va.no_video_upscaler_megapixels', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-align-20260825', 'h3-ref2va.no_video_upscaler_align', 'CONFIGURE_IN_ADMIN', 'number', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-chunking-20260825', 'h3-ref2va.no_video_upscaler_chunking', 'false', 'boolean', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-device-20260825', 'h3-ref2va.no_video_upscaler_device', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('h3-ref2va-no-video-upscaler-precision-20260825', 'h3-ref2va.no_video_upscaler_precision', 'CONFIGURE_IN_ADMIN', 'string', 'h3-ref2va', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

DELETE FROM system_settings WHERE key IN (
  'h3-fl2va.attention_backend',
  'h3-fl2va.fused_modulation',
  'h3-fl2va.sol_attn_enabled',
  'h3-fl2va.sol_attn_tau_start',
  'h3-fl2va.sol_attn_tau_end',
  'h3-fl2va.sol_attn_curve',
  'h3-fl2va.sol_attn_min_len',
  'h3-fl2va.sol_attn_strict',
  'h3-fl2va.sol_attn_dense_percent',
  'h3-fl2va.sol_attn_thresh_type',
  'h3-fl2va.sol_attn_int8_qk',
  'h3-fl2va.sol_attn_int8_pv',
  'h3-fl2va.sol_attn_sink_conditioning',
  'h3-fl2va.sol_attn_dense_blocks',
  'h3-ref2va.attention_backend',
  'h3-ref2va.fused_modulation',
  'h3-ref2va.sol_attn_enabled',
  'h3-ref2va.sol_attn_tau_start',
  'h3-ref2va.sol_attn_tau_end',
  'h3-ref2va.sol_attn_curve',
  'h3-ref2va.sol_attn_min_len',
  'h3-ref2va.sol_attn_strict',
  'h3-ref2va.sol_attn_dense_percent',
  'h3-ref2va.sol_attn_thresh_type',
  'h3-ref2va.sol_attn_int8_qk',
  'h3-ref2va.sol_attn_int8_pv',
  'h3-ref2va.sol_attn_sink_conditioning',
  'h3-ref2va.sol_attn_dense_blocks',
  'h3-ref2va.steps_with_video',
  'h3-ref2va.megapixels_with_video'
);
