// Node ID ↔ class type details: Docs/workflow-node-map.md
export const LTX = {
  AUDIO_VAE: '1',
  VIDEO_VAE: '2',
  POSITIVE_PROMPT: '5',
  NEGATIVE_PROMPT: '6',
  FRAME_RATE_INT: '11',
  FRAME_RATE_FLOAT: '12',
  NOISE_SEED: '16',
  SAMPLER: '20',
  CLIP: '47',
  NAG: '72',
  RESIZE: '86',
  LOAD_IMAGE: '87',
  DURATION: '103',
  LOAD_IMAGE_END: '260',
  RESIZE_END_IMAGE: '264',
  END_IMAGE_CONFIG: '265',
  LORA_PLACEHOLDER: '296',
  UNET: '297',
  SAGE_ATTENTION: '298',
  AUDIO_NORM: '317',
  VIDEO_OUTPUT: '319',
  RTX_SUPER_RES: '322',
  SIGMAS: '335',
  VFI: '337',
  VFI_MULTIPLIER: '339',
} as const
