import type { ComfyUIWorkflow } from '@/types'

export const H3_FL2VA_WORKFLOW_TEMPLATE = {
  '1': { inputs: { shift_video: 0, shift_audio: 0, model: ['7', 0] }, class_type: 'MiniMaxH3SigmaShift', _meta: { title: 'ModelSamplingMiniMaxH3' } },
  '7': { inputs: { unet_name: 'PLACEHOLDER', weight_dtype: 'PLACEHOLDER' }, class_type: 'UNETLoader', _meta: { title: 'Load Diffusion Model' } },
  '13': { inputs: { image: 'PLACEHOLDER' }, class_type: 'LoadImage', _meta: { title: 'Load Image' } },
  '14': {
    inputs: { megapixels: 0, multiple_of: 0, upscale_method: 'PLACEHOLDER', image: ['13', 0] },
    class_type: 'ResizeImageToMegapixels',
    _meta: { title: 'Resize Image (Megapixels + Alignment)' },
  },
  '15': { inputs: { vae_name: 'PLACEHOLDER' }, class_type: 'VAELoader', _meta: { title: 'Load VAE' } },
  '16': { inputs: { vae_name: 'PLACEHOLDER' }, class_type: 'VAELoader', _meta: { title: 'Load VAE' } },
  '17': { inputs: { clip_name: 'PLACEHOLDER', type: 'PLACEHOLDER', device: 'PLACEHOLDER' }, class_type: 'CLIPLoader', _meta: { title: 'Load CLIP' } },
  '18': { inputs: { positive: 'PLACEHOLDER' }, class_type: 'easy positive', _meta: { title: 'Positive' } },
  '19': { inputs: { value: 0 }, class_type: 'PrimitiveInt', _meta: { title: 'Steps' } },
  '20': { inputs: { expression: 'PLACEHOLDER', a: ['21', 0] }, class_type: 'MathExpression|pysssss', _meta: { title: 'Generate Frame' } },
  '21': { inputs: { value: 0 }, class_type: 'PrimitiveInt', _meta: { title: 'N' } },
  '22': { inputs: { number_type: 'float', number: 0 }, class_type: 'Constant Number', _meta: { title: 'FPS' } },
  '23': { inputs: { model: ['52', 0], conditioning: ['29', 0] }, class_type: 'BasicGuider', _meta: { title: 'Basic Guider' } },
  '24': {
    inputs: { noise: ['25', 0], guider: ['23', 0], sampler: ['26', 0], sigmas: ['55', 0], latent_image: ['69', 1] },
    class_type: 'SamplerCustomAdvanced',
    _meta: { title: 'SamplerCustomAdvanced' },
  },
  '25': { inputs: { noise_seed: 0 }, class_type: 'RandomNoise', _meta: { title: 'RandomNoise' } },
  '26': { inputs: { sampler_name: 'PLACEHOLDER' }, class_type: 'KSamplerSelect', _meta: { title: 'KSamplerSelect' } },
  '27': {
    inputs: { scheduler: 'PLACEHOLDER', steps: ['19', 0], denoise: 1, model: ['52', 0] },
    class_type: 'BasicScheduler',
    _meta: { title: 'BasicScheduler' },
  },
  '28': { inputs: { av_latent: ['30', 0] }, class_type: 'LTXVSeparateAVLatent', _meta: { title: 'LTXVSeparateAVLatent' } },
  '29': {
    inputs: { verbose: true, release_pinned_ram: true, aimdo_analyze: true, passthrough: ['69', 0] },
    class_type: 'ForceFullUnload',
    _meta: { title: 'Force Full Unload (VRAM+Pinned)' },
  },
  '30': {
    inputs: { verbose: true, release_pinned_ram: true, aimdo_analyze: true, passthrough: ['24', 1] },
    class_type: 'ForceFullUnload',
    _meta: { title: 'Force Full Unload (VRAM+Pinned)' },
  },
  '31': { inputs: { samples: ['62', 0], vae: ['16', 0] }, class_type: 'VAEDecode', _meta: { title: 'VAE Decode' } },
  '32': { inputs: { samples: ['62', 1], vae: ['15', 0] }, class_type: 'VAEDecodeAudio', _meta: { title: 'VAE Decode Audio' } },
  '33': {
    inputs: { resize_type: 'PLACEHOLDER', 'resize_type.scale': 0, quality: 'PLACEHOLDER', images: ['31', 0] },
    class_type: 'RTXVideoSuperResolution',
    _meta: { title: 'RTX Video Super Resolution' },
  },
  '34': {
    inputs: {
      frame_rate: ['22', 1],
      loop_count: 0,
      filename_prefix: 'PLACEHOLDER',
      format: 'PLACEHOLDER',
      pix_fmt: 'PLACEHOLDER',
      crf: 0,
      save_metadata: false,
      trim_to_audio: false,
      pingpong: false,
      save_output: false,
      images: ['33', 0],
      audio: ['32', 0],
    },
    class_type: 'VHS_VideoCombine',
    _meta: { title: 'Video Combine 🎥🅥🅗🅢' },
  },
  '40': {
    inputs: { verbose: true, release_pinned_ram: true, aimdo_analyze: true, passthrough: ['34', 0] },
    class_type: 'ForceFullUnload',
    _meta: { title: 'Force Full Unload (VRAM+Pinned)' },
  },
  '49': { inputs: { head_chunks: 0, model: ['50', 0] }, class_type: 'MiniMaxLowVRAMAttention', _meta: { title: 'MiniMax H3 Low VRAM Attention' } },
  '50': { inputs: { attention_mode: 'PLACEHOLDER', model: ['1', 0] }, class_type: 'MiniMaxH3MemoryEfficientSageAttentionPatch', _meta: { title: 'MiniMax H3 Mem Eff Sage Attention Patch' } },
  '52': {
    inputs: { enabled: false, chunks: 0, min_tokens: 0, model: ['49', 0] },
    class_type: 'MiniMaxH3ChunkFeedForward',
    _meta: { title: 'MiniMax H3 Chunk FeedForward' },
  },
  '55': { inputs: { step: 0, sigmas: ['27', 0] }, class_type: 'SplitSigmas', _meta: { title: 'SplitSigmas' } },
  '57': {
    inputs: {
      model_name: 'PLACEHOLDER',
      mode: 'target dimensions',
      'mode.width': ['73', 1],
      'mode.height': ['73', 2],
      align: 0,
      enable_chunking: false,
      device: 'PLACEHOLDER',
      precision: 'PLACEHOLDER',
      latent: ['28', 0],
    },
    class_type: 'MinimaxH3LatentUpscaler3D',
    _meta: { title: 'Minimax H3 Latent Upscaler (3D)' },
  },
  '58': { inputs: { video_latent: ['57', 0], audio_latent: ['28', 1] }, class_type: 'LTXVConcatAVLatent', _meta: { title: 'LTXVConcatAVLatent' } },
  '59': {
    inputs: { noise: ['25', 0], guider: ['74', 0], sampler: ['26', 0], sigmas: ['66', 0], latent_image: ['58', 0] },
    class_type: 'SamplerCustomAdvanced',
    _meta: { title: 'SamplerCustomAdvanced' },
  },
  '61': {
    inputs: { verbose: true, release_pinned_ram: true, aimdo_analyze: true, passthrough: ['59', 0] },
    class_type: 'ForceFullUnload',
    _meta: { title: 'Force Full Unload (VRAM+Pinned)' },
  },
  '62': { inputs: { av_latent: ['61', 0] }, class_type: 'LTXVSeparateAVLatent', _meta: { title: 'LTXVSeparateAVLatent' } },
  '66': { inputs: { sigmas: 'PLACEHOLDER' }, class_type: 'ManualSigmas', _meta: { title: 'ManualSigmas' } },
  '69': {
    inputs: { prompt: ['18', 0], width: ['14', 1], height: ['14', 2], length: ['20', 0], clip: ['17', 0], vae: ['16', 0], first_frame: ['14', 0] },
    class_type: 'MiniMaxH3ImageToVideo',
    _meta: { title: 'MiniMax H3 Image to Video' },
  },
  '72': {
    inputs: { prompt: ['18', 0], width: ['73', 1], height: ['73', 2], length: ['20', 0], clip: ['17', 0], vae: ['16', 0], first_frame: ['73', 0] },
    class_type: 'MiniMaxH3ImageToVideo',
    _meta: { title: 'MiniMax H3 Image to Video' },
  },
  '73': {
    inputs: { megapixels: 0, multiple_of: 0, upscale_method: 'PLACEHOLDER', image: ['13', 0] },
    class_type: 'ResizeImageToMegapixels',
    _meta: { title: 'Resize Image (Megapixels + Alignment)' },
  },
  '74': { inputs: { model: ['52', 0], conditioning: ['72', 0] }, class_type: 'BasicGuider', _meta: { title: 'Basic Guider' } },
  '80': { inputs: { image: 'PLACEHOLDER' }, class_type: 'LoadImage', _meta: { title: 'Last Frame' } },
  '81': {
    inputs: { megapixels: 0, multiple_of: 0, upscale_method: 'PLACEHOLDER', image: ['80', 0] },
    class_type: 'ResizeImageToMegapixels',
    _meta: { title: 'Resize Image (Megapixels + Alignment)' },
  },
  '82': {
    inputs: { megapixels: 0, multiple_of: 0, upscale_method: 'PLACEHOLDER', image: ['80', 0] },
    class_type: 'ResizeImageToMegapixels',
    _meta: { title: 'Resize Image (Megapixels + Alignment)' },
  },
} satisfies ComfyUIWorkflow
