export const LTX_WAN = {
  // === LTX Pass — Input ===
  LOAD_IMAGE_START: '8',
  RESIZE_START: '25',
  LOAD_IMAGE_END: '6',
  RESIZE_END: '20',
  PREPROCESS_START: '17',
  PREPROCESS_END: '1',

  // === LTX Pass — Models & Encoding ===
  UNET: '30',
  SAGE_ATTENTION: '21',
  CLIP: '39',
  VIDEO_VAE: '38',
  AUDIO_VAE: '37',
  POWER_LORA: '33',
  FRAME_RATE: '3',
  DURATION: '36',
  FRAME_COUNT_MATH: '2',

  // === LTX Pass — Conditioning & Sampling ===
  POSITIVE_PROMPT: '55',
  NEGATIVE_PROMPT_LTX: '161',
  CLIP_ENCODE_POS: '13',
  CLIP_ENCODE_NEG: '27',
  CONDITIONING: '7',
  REFERENCE_AUDIO: '28',
  LOAD_AUDIO: '14',
  NAG_LTX: '23',
  AUDIO_NORM: '157',
  CFG_GUIDER: '29',
  EMPTY_LATENT_VIDEO: '19',
  EMPTY_LATENT_AUDIO: '9',
  IMG_TO_VIDEO: '18',
  END_FRAME_MATH: '31',
  CONCAT_AV: '24',
  SCHEDULER: '32',
  CLOWN_SAMPLER_LTX: '41',
  NOISE_SEED_LTX: '42',
  SAMPLER_LTX: '12',

  // === LTX Pass — Decode ===
  SEPARATE_AV: '16',
  VAE_DECODE_LTX: '10',
  AUDIO_DECODE: '11',

  // === WAN Pass — WanVideo Suite ===
  WAN_SAMPLER: '205',
  WAN_MODEL_LOADER: '206',
  WAN_VAE_LOADER: '207',
  WAN_VAE_DECODE: '208',
  WAN_T5_ENCODER: '212',
  WAN_NAG: '213',
  NEGATIVE_PROMPT_WAN: '56',
  WAN_TEXT_ENCODE_POS: '214',
  WAN_TEXT_ENCODE_NEG: '215',
  WAN_VAE_ENCODE: '217',
  WAN_CONTEXT_OPTIONS: '218',
  WAN_BLOCK_SWAP_SET: '221',
  WAN_BLOCK_SWAP: '222',
  WAN_MANUAL_SIGMAS: '228',
  WAN_I2V_ENCODE: '230',

  // === Force Full Unload (memory release checkpoints) ===
  FORCE_UNLOAD_CONDITIONING: '197',
  FORCE_UNLOAD_SAMPLER_LTX: '188',
  FORCE_UNLOAD_VAE_LTX: '187',
  FORCE_UNLOAD_AUDIO: '194',
  FORCE_UNLOAD_SAMPLER_WAN: '189',
  FORCE_UNLOAD_VAE_WAN: '198',
  FORCE_UNLOAD_OUTPUT: '190',

  // === Post Processing ===
  VFI_MULTIPLIER: '34',
  VFI: '168',
  RIFE_MODEL_LOADER: '169',
  RIFE_CUSTOM_CONFIG: '170',
  RTX_SUPER_RES: '84',
  VFI_FRAME_RATE: '35',

  // === Output ===
  VIDEO_OUTPUT: '82',
} as const
