import { prisma } from '@/lib/database/prisma'

type SeedType = 'string' | 'number' | 'boolean'

const fakeSfwLoraChain = JSON.stringify([
  {
    id: 'fake-sfw-chain-1',
    enabled: true,
    name: 'fake-ltx-sfw-chain-a.safetensors',
    strength: 0.51,
    video: 0.11,
    videoToAudio: 0.12,
    audio: 0.13,
    audioToVideo: 0.14,
    other: 0.15,
  },
  {
    id: 'fake-sfw-chain-2',
    enabled: false,
    name: 'fake-ltx-sfw-chain-disabled.safetensors',
    strength: 0.62,
    video: 0.21,
    videoToAudio: 0.22,
    audio: 0.23,
    audioToVideo: 0.24,
    other: 0.25,
  },
  {
    id: 'fake-sfw-chain-3',
    enabled: true,
    name: 'fake-ltx-sfw-chain-c.safetensors',
    strength: 0.73,
    video: 0.31,
    videoToAudio: 0.32,
    audio: 0.33,
    audioToVideo: 0.34,
    other: 0.35,
  },
])

const fakeNsfwLoraChain = JSON.stringify([
  {
    id: 'fake-nsfw-chain-1',
    enabled: true,
    name: 'fake-ltx-nsfw-chain-a.safetensors',
    strength: 0.56,
    video: 0.16,
    videoToAudio: 0.17,
    audio: 0.18,
    audioToVideo: 0.19,
    other: 0.2,
  },
  {
    id: 'fake-nsfw-chain-2',
    enabled: true,
    name: 'fake-ltx-nsfw-chain-b.safetensors',
    strength: 0.67,
    video: 0.26,
    videoToAudio: 0.27,
    audio: 0.28,
    audioToVideo: 0.29,
    other: 0.3,
  },
])

export const LTX_SEED: Array<{ key: string; value: string; type: SeedType }> = [
  { key: 'ltx.enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_enabled', value: 'false', type: 'boolean' },
  { key: 'ltx.end_image_enabled', value: 'false', type: 'boolean' },
  { key: 'ltx.checkpoint', value: 'fake-ltx-checkpoint-q7m.safetensors', type: 'string' },
  { key: 'ltx.text_encoder', value: 'fake-ltx-text-encoder-p4v.safetensors', type: 'string' },
  { key: 'ltx.negative_prompt', value: 'fake negative prompt z8r', type: 'string' },
  { key: 'ltx.video_conditioning_prompt', value: 'fake video conditioning prompt h2k', type: 'string' },
  { key: 'ltx.audio_conditioning_prompt', value: 'fake audio conditioning prompt m9t', type: 'string' },
  { key: 'ltx.frame_rate', value: '18', type: 'number' },
  { key: 'ltx.duration_options', value: '4,8,12', type: 'string' },
  { key: 'ltx.frame_base', value: '10', type: 'number' },
  { key: 'ltx.megapixels', value: '0.73', type: 'number' },
  { key: 'ltx.resize_multiple_of', value: '24', type: 'number' },
  { key: 'ltx.resize_upscale_method', value: 'fake-resize-method', type: 'string' },
  { key: 'ltx.sampler', value: 'fake-sampler-r6d', type: 'string' },
  { key: 'ltx.clown_eta', value: '0.17', type: 'number' },
  { key: 'ltx.clown_bongmath', value: 'true', type: 'boolean' },
  { key: 'ltx.scheduler_steps', value: '13', type: 'number' },
  { key: 'ltx.scheduler_max_shift', value: '1.37', type: 'number' },
  { key: 'ltx.scheduler_base_shift', value: '0.41', type: 'number' },
  { key: 'ltx.scheduler_stretch', value: 'false', type: 'boolean' },
  { key: 'ltx.scheduler_terminal', value: '0.23', type: 'number' },
  { key: 'ltx.nag_scale', value: '3.4', type: 'number' },
  { key: 'ltx.nag_alpha', value: '0.19', type: 'number' },
  { key: 'ltx.nag_tau', value: '1.61', type: 'number' },
  { key: 'ltx.identity_guidance_scale', value: '2.7', type: 'number' },
  { key: 'ltx.identity_start_percent', value: '0.12', type: 'number' },
  { key: 'ltx.identity_end_percent', value: '0.86', type: 'number' },
  { key: 'ltx.guide_frame_index', value: '3', type: 'number' },
  { key: 'ltx.guide_strength', value: '0.46', type: 'number' },
  { key: 'ltx.guide_crf', value: '27', type: 'number' },
  { key: 'ltx.guide_blur_radius', value: '5', type: 'number' },
  { key: 'ltx.guide_interpolation', value: 'fake-guide-interpolation', type: 'string' },
  { key: 'ltx.guide_crop', value: 'fake-guide-crop', type: 'string' },
  { key: 'ltx.anchor_strength', value: '0.31', type: 'number' },
  { key: 'ltx.anchor_cache_at_step', value: '4', type: 'number' },
  { key: 'ltx.anchor_similarity_threshold', value: '0.62', type: 'number' },
  { key: 'ltx.anchor_decay_with_distance', value: '0.27', type: 'number' },
  { key: 'ltx.anchor_energy_threshold', value: '0.18', type: 'number' },
  { key: 'ltx.anchor_bypass', value: 'true', type: 'boolean' },
  { key: 'ltx.anchor_debug', value: 'false', type: 'boolean' },
  { key: 'ltx.anchor_advanced_mode', value: 'true', type: 'boolean' },
  { key: 'ltx.anchor_cache_mode', value: 'fake-anchor-cache-mode', type: 'string' },
  { key: 'ltx.anchor_forwards_per_step', value: '2', type: 'number' },
  { key: 'ltx.anchor_cache_warmup', value: '6', type: 'number' },
  { key: 'ltx.anchor_frame', value: '1', type: 'number' },
  { key: 'ltx.anchor_depth_curve', value: 'fake-anchor-depth-curve', type: 'string' },
  { key: 'ltx.anchor_block_index_filter', value: 'fake-block-filter-2,4,6', type: 'string' },
  { key: 'ltx.latent_upscale_model', value: 'fake-ltx-latent-upscaler-u8p.safetensors', type: 'string' },
  { key: 'ltx.text_attention_amplification', value: '1.37', type: 'number' },
  { key: 'ltx.multimodal_video_cfg', value: '2.41', type: 'number' },
  { key: 'ltx.multimodal_audio_cfg', value: '4.73', type: 'number' },
  { key: 'ltx.multimodal_inactive_cfg', value: '0.83', type: 'number' },
  { key: 'ltx.multimodal_active_steps', value: '3', type: 'number' },
  { key: 'ltx.second_pass_cfg', value: '1.29', type: 'number' },
  { key: 'ltx.second_pass_sigmas', value: 'fake-second-pass-sigmas-q5m', type: 'string' },
  { key: 'ltx.second_pass_upscale_method', value: 'fake-second-pass-upscale-method', type: 'string' },
  { key: 'ltx.second_pass_upscale_by', value: '1.75', type: 'number' },
  { key: 'ltx.second_pass_anchor_strength', value: '0.24', type: 'number' },
  { key: 'ltx.second_pass_anchor_cache_at_step', value: '7', type: 'number' },
  { key: 'ltx.second_pass_anchor_similarity_threshold', value: '0.58', type: 'number' },
  { key: 'ltx.second_pass_anchor_decay_with_distance', value: '0.14', type: 'number' },
  { key: 'ltx.second_pass_anchor_energy_threshold', value: '0.22', type: 'number' },
  { key: 'ltx.second_pass_anchor_bypass', value: 'false', type: 'boolean' },
  { key: 'ltx.second_pass_anchor_debug', value: 'true', type: 'boolean' },
  { key: 'ltx.second_pass_anchor_advanced_mode', value: 'true', type: 'boolean' },
  { key: 'ltx.second_pass_anchor_cache_mode', value: 'fake-second-pass-anchor-cache-mode', type: 'string' },
  { key: 'ltx.second_pass_anchor_forwards_per_step', value: '3', type: 'number' },
  { key: 'ltx.second_pass_anchor_cache_warmup', value: '9', type: 'number' },
  { key: 'ltx.second_pass_anchor_frame', value: '2', type: 'number' },
  { key: 'ltx.second_pass_anchor_depth_curve', value: 'fake-second-pass-anchor-depth-curve', type: 'string' },
  { key: 'ltx.second_pass_anchor_block_index_filter', value: 'fake-second-pass-block-filter-1,3,5', type: 'string' },
  { key: 'ltx.rtx_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.rtx_resize_type', value: 'fake-rtx-resize-type', type: 'string' },
  { key: 'ltx.rtx_scale', value: '1.5', type: 'number' },
  { key: 'ltx.rtx_quality', value: 'fake-rtx-quality', type: 'string' },
  { key: 'ltx.sfw_lora_chain', value: fakeSfwLoraChain, type: 'string' },
  { key: 'ltx.nsfw_lora_chain', value: fakeNsfwLoraChain, type: 'string' },
  { key: 'ltx.id_lora_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.id_lora_name', value: 'fake-ltx-id-lora-v9n.safetensors', type: 'string' },
  { key: 'ltx.id_lora_strength', value: '0.91', type: 'number' },
  { key: 'ltx.id_lora_video', value: '0.51', type: 'number' },
  { key: 'ltx.id_lora_video_to_audio', value: '0.52', type: 'number' },
  { key: 'ltx.id_lora_audio', value: '0.53', type: 'number' },
  { key: 'ltx.id_lora_audio_to_video', value: '0.54', type: 'number' },
  { key: 'ltx.id_lora_other', value: '0.55', type: 'number' },
  { key: 'ltx.video_crf', value: '29', type: 'number' },
  { key: 'ltx.video_format', value: 'fake-video-format', type: 'string' },
  { key: 'ltx.video_pix_fmt', value: 'fake-pix-fmt', type: 'string' },
]

export async function seedLtx(): Promise<void> {
  await prisma.systemSetting.createMany({
    data: LTX_SEED.map((row) => ({
      key: row.key,
      value: row.value,
      type: row.type,
      category: 'ltx',
    })),
  })
}
