import { prisma } from '@/lib/database/prisma'

type SeedType = 'string' | 'number' | 'boolean'

export const LTX_SEED: Array<{ key: string; value: string; type: SeedType }> = [
  { key: 'ltx.enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_enabled', value: 'false', type: 'boolean' },
  { key: 'ltx.checkpoint', value: 'fake-ltx-checkpoint-q7m.safetensors', type: 'string' },
  { key: 'ltx.text_encoder', value: 'fake-ltx-text-encoder-p4v.safetensors', type: 'string' },
  { key: 'ltx.negative_prompt', value: 'fake negative prompt z8r', type: 'string' },
  { key: 'ltx.video_conditioning_prompt', value: 'fake video conditioning prompt h2k', type: 'string' },
  { key: 'ltx.audio_conditioning_prompt', value: 'fake audio conditioning prompt m9t', type: 'string' },
  { key: 'ltx.frame_rate', value: '18', type: 'number' },
  { key: 'ltx.duration_options', value: '4,8,12', type: 'string' },
  { key: 'ltx.frame_base', value: '10', type: 'number' },
  { key: 'ltx.megapixels', value: '0.73', type: 'number' },
  { key: 'ltx.resize_multiple_of', value: '24', type: 'number' },
  { key: 'ltx.resize_upscale_method', value: 'fake-resize-method', type: 'string' },
  { key: 'ltx.sampler', value: 'fake-sampler-r6d', type: 'string' },
  { key: 'ltx.clown_eta', value: '0.17', type: 'number' },
  { key: 'ltx.clown_bongmath', value: 'true', type: 'boolean' },
  { key: 'ltx.scheduler_steps', value: '13', type: 'number' },
  { key: 'ltx.scheduler_max_shift', value: '1.37', type: 'number' },
  { key: 'ltx.scheduler_base_shift', value: '0.41', type: 'number' },
  { key: 'ltx.scheduler_stretch', value: 'false', type: 'boolean' },
  { key: 'ltx.scheduler_terminal', value: '0.23', type: 'number' },
  { key: 'ltx.nag_scale', value: '3.4', type: 'number' },
  { key: 'ltx.nag_alpha', value: '0.19', type: 'number' },
  { key: 'ltx.nag_tau', value: '1.61', type: 'number' },
  { key: 'ltx.identity_guidance_scale', value: '2.7', type: 'number' },
  { key: 'ltx.identity_start_percent', value: '0.12', type: 'number' },
  { key: 'ltx.identity_end_percent', value: '0.86', type: 'number' },
  { key: 'ltx.guide_frame_index', value: '3', type: 'number' },
  { key: 'ltx.guide_strength', value: '0.46', type: 'number' },
  { key: 'ltx.guide_crf', value: '27', type: 'number' },
  { key: 'ltx.guide_blur_radius', value: '5', type: 'number' },
  { key: 'ltx.guide_interpolation', value: 'fake-guide-interpolation', type: 'string' },
  { key: 'ltx.guide_crop', value: 'fake-guide-crop', type: 'string' },
  { key: 'ltx.anchor_strength', value: '0.31', type: 'number' },
  { key: 'ltx.anchor_cache_at_step', value: '4', type: 'number' },
  { key: 'ltx.anchor_similarity_threshold', value: '0.62', type: 'number' },
  { key: 'ltx.anchor_decay_with_distance', value: '0.27', type: 'number' },
  { key: 'ltx.anchor_energy_threshold', value: '0.18', type: 'number' },
  { key: 'ltx.anchor_bypass', value: 'true', type: 'boolean' },
  { key: 'ltx.anchor_debug', value: 'false', type: 'boolean' },
  { key: 'ltx.anchor_advanced_mode', value: 'true', type: 'boolean' },
  { key: 'ltx.anchor_cache_mode', value: 'fake-anchor-cache-mode', type: 'string' },
  { key: 'ltx.anchor_forwards_per_step', value: '2', type: 'number' },
  { key: 'ltx.anchor_cache_warmup', value: '6', type: 'number' },
  { key: 'ltx.anchor_frame', value: '1', type: 'number' },
  { key: 'ltx.anchor_depth_curve', value: 'fake-anchor-depth-curve', type: 'string' },
  { key: 'ltx.anchor_block_index_filter', value: 'fake-block-filter-2,4,6', type: 'string' },
  { key: 'ltx.scheduled_cfg', value: '2.2', type: 'number' },
  { key: 'ltx.scheduled_cfg_start_percent', value: '0.08', type: 'number' },
  { key: 'ltx.scheduled_cfg_end_percent', value: '0.77', type: 'number' },
  { key: 'ltx.lora_1_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_1_name', value: 'fake-ltx-lora-slot1-a1q.safetensors', type: 'string' },
  { key: 'ltx.lora_1_strength', value: '0.51', type: 'number' },
  { key: 'ltx.lora_1_video', value: '0.11', type: 'number' },
  { key: 'ltx.lora_1_video_to_audio', value: '0.12', type: 'number' },
  { key: 'ltx.lora_1_audio', value: '0.13', type: 'number' },
  { key: 'ltx.lora_1_audio_to_video', value: '0.14', type: 'number' },
  { key: 'ltx.lora_1_other', value: '0.15', type: 'number' },
  { key: 'ltx.lora_2_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_2_name', value: 'fake-ltx-lora-slot2-b2w.safetensors', type: 'string' },
  { key: 'ltx.lora_2_strength', value: '0.62', type: 'number' },
  { key: 'ltx.lora_2_video', value: '0.21', type: 'number' },
  { key: 'ltx.lora_2_video_to_audio', value: '0.22', type: 'number' },
  { key: 'ltx.lora_2_audio', value: '0.23', type: 'number' },
  { key: 'ltx.lora_2_audio_to_video', value: '0.24', type: 'number' },
  { key: 'ltx.lora_2_other', value: '0.25', type: 'number' },
  { key: 'ltx.lora_3_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_3_name', value: 'fake-ltx-lora-slot3-c3e.safetensors', type: 'string' },
  { key: 'ltx.lora_3_strength', value: '0.73', type: 'number' },
  { key: 'ltx.lora_3_video', value: '0.31', type: 'number' },
  { key: 'ltx.lora_3_video_to_audio', value: '0.32', type: 'number' },
  { key: 'ltx.lora_3_audio', value: '0.33', type: 'number' },
  { key: 'ltx.lora_3_audio_to_video', value: '0.34', type: 'number' },
  { key: 'ltx.lora_3_other', value: '0.35', type: 'number' },
  { key: 'ltx.lora_4_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.lora_4_name', value: 'fake-ltx-lora-slot4-d4r.safetensors', type: 'string' },
  { key: 'ltx.lora_4_strength', value: '0.84', type: 'number' },
  { key: 'ltx.lora_4_video', value: '0.41', type: 'number' },
  { key: 'ltx.lora_4_video_to_audio', value: '0.42', type: 'number' },
  { key: 'ltx.lora_4_audio', value: '0.43', type: 'number' },
  { key: 'ltx.lora_4_audio_to_video', value: '0.44', type: 'number' },
  { key: 'ltx.lora_4_other', value: '0.45', type: 'number' },
  { key: 'ltx.rtx_enabled', value: 'true', type: 'boolean' },
  { key: 'ltx.rtx_resize_type', value: 'fake-rtx-resize-type', type: 'string' },
  { key: 'ltx.rtx_scale', value: '1.6', type: 'number' },
  { key: 'ltx.rtx_quality', value: 'fake-rtx-quality', type: 'string' },
  { key: 'ltx.video_crf', value: '29', type: 'number' },
  { key: 'ltx.video_format', value: 'fake-video-format', type: 'string' },
  { key: 'ltx.video_pix_fmt', value: 'fake-pix-fmt', type: 'string' },
]

export async function seedLtx(): Promise<void> {
  await prisma.systemSetting.createMany({
    data: LTX_SEED.map((row) => ({
      key: row.key,
      value: row.value,
      type: row.type,
      category: 'ltx',
    })),
  })
}
